### ISSUE TITLE
Eclipse project VCS meta-data incorrect

### ISSUE THREAD

**Issue by jrwilliams** [ossmeter/ossmeter#13]
Recently Eclipse migrated all (remaining) projects to Git. It appears, however, that the API used by the Eclipse importer still shows some projects as having SVN repos. When the platform tries to analyse these repos, it understandably throws an exception. 

Options:
- Try analysing all projects, log SVN-related errors and manually update meta-data to new Git repo
- Contact Eclipse and ask the meta-data to be updated
- Write a script that iterates all Eclipse projects, checks for SVN repos, and updates them to Git (assuming naming conventions for Git repos are consistent)

**Comment by jrwilliams** [comment]
It appears that I spoke too soon, as this has now been fixed by Eclipse :)

**Comment by jrwilliams** [comment]
Turns out I spoke too soon again! Only some of the projects' meta-data have been updated. A complete list of projects with invalid VCS info:
- https://projects.eclipse.org/projects/technology.rtsc/developer
- https://projects.eclipse.org/projects/modeling.gmt.amw/developer
- https://projects.eclipse.org/projects/soa.jwt/developer
- https://projects.eclipse.org/projects/tools.windowbuilder/developer
- https://projects.eclipse.org/projects/technology.higgins/developer
- https://projects.eclipse.org/projects/soa.ebpm/developer
- https://projects.eclipse.org/projects/technology.vtp/developer
- https://projects.eclipse.org/projects/soa.ebam/developer

However this one has a valid SVN repo:
https://projects.eclipse.org/projects/technology.subversive/developer

**Comment by jdirocco** [comment]
Check svn url before add a VCS. If svn url doesn't exist check if the vcs are migrated into Git repository.
