### ISSUE TITLE
Deployment issue

### ISSUE THREAD

**Issue by tteixeira** [ossmeter/ossmeter#2]
When trying to deploy the platform we had 2 more errors regarding plugins that were not found:
- "org.eclipse.imp.pdb.values"
- "org.eclipse.core.filesystem.macosx"

We tried removing them from feature.xml and now we have different erros:

---

/home/ossmeter/workspace/.metadata/.plugins/org.eclipse.pde.core/temp/org.eclipse.pde.container.feature/assemble.org.eclipse.pde.container.feature.p2.xml:41: The following error occurred while executing this line:
/home/ossmeter/workspace/.metadata/.plugins/org.eclipse.pde.core/temp/org.eclipse.pde.container.feature/assemble.org.eclipse.pde.container.feature.p2.xml:51: The following error occurred while executing this line:
/home/ossmeter/workspace/.metadata/.plugins/org.eclipse.pde.core/temp/org.eclipse.pde.container.feature/assemble.org.eclipse.pde.container.feature.p2.xml:27: The following error occurred while executing this line:
/home/ossmeter/ossmeter/platform-extensions/org.ossmeter.platform.metricmanager.rascal/build.xml:257: The following error occurred while executing this line:
/home/ossmeter/ossmeter/platform-extensions/org.ossmeter.platform.metricmanager.rascal/build.xml:368: Problem: failed to create task or type apitooling.apigeneration
Cause: The name is undefined.
Action: Check the spelling.
Action: Check that any custom tasks/types have been declared.
Action: Check that any <presetdef>/<macrodef> declarations have taken place.

The following error occurred while executing this line:
/home/ossmeter/workspace/.metadata/.plugins/org.eclipse.pde.core/temp/org.eclipse.pde.container.feature/assemble.org.eclipse.pde.container.feature.p2.xml:51: The following error occurred while executing this line:
/home/ossmeter/workspace/.metadata/.plugins/org.eclipse.pde.core/temp/org.eclipse.pde.container.feature/assemble.org.eclipse.pde.container.feature.p2.xml:27: The following error occurred while executing this line:
/home/ossmeter/ossmeter/platform-extensions/org.ossmeter.platform.metricmanager.rascal/build.xml:257: The following error occurred while executing this line:
/home/ossmeter/ossmeter/platform-extensions/org.ossmeter.platform.metricmanager.rascal/build.xml:368: Problem: failed to create task or type apitooling.apigeneration
Cause: The name is undefined.
Action: Check the spelling.
Action: Check that any custom tasks/types have been declared.
Action: Check that any <presetdef>/<macrodef> declarations have taken place.
------- (with "Generate p2 repository" checked)

---

/home/ossmeter/workspace/.metadata/.plugins/org.eclipse.pde.core/temp/org.eclipse.pde.container.feature/assemble.org.eclipse.pde.container.feature.linux.gtk.x86_64.xml:89: The following error occurred while executing this line:
/home/ossmeter/workspace/.metadata/.plugins/org.eclipse.pde.core/temp/org.eclipse.pde.container.feature/assemble.org.eclipse.pde.container.feature.linux.gtk.x86_64.xml:104: The following error occurred while executing this line:
/home/ossmeter/workspace/.metadata/.plugins/org.eclipse.pde.core/temp/org.eclipse.pde.container.feature/assemble.org.eclipse.pde.container.feature.linux.gtk.x86_64.xml:27: The following error occurred while executing this line:
/home/ossmeter/ossmeter/platform-extensions/org.ossmeter.platform.metricmanager.rascal/build.xml:293: The following error occurred while executing this line:
/home/ossmeter/ossmeter/platform-extensions/org.ossmeter.platform.metricmanager.rascal/build.xml:368: Problem: failed to create task or type apitooling.apigeneration
Cause: The name is undefined.
Action: Check the spelling.
Action: Check that any custom tasks/types have been declared.
Action: Check that any <presetdef>/<macrodef> declarations have taken place.

The following error occurred while executing this line:
/home/ossmeter/workspace/.metadata/.plugins/org.eclipse.pde.core/temp/org.eclipse.pde.container.feature/assemble.org.eclipse.pde.container.feature.linux.gtk.x86_64.xml:104: The following error occurred while executing this line:
/home/ossmeter/workspace/.metadata/.plugins/org.eclipse.pde.core/temp/org.eclipse.pde.container.feature/assemble.org.eclipse.pde.container.feature.linux.gtk.x86_64.xml:27: The following error occurred while executing this line:
/home/ossmeter/ossmeter/platform-extensions/org.ossmeter.platform.metricmanager.rascal/build.xml:293: The following error occurred while executing this line:
/home/ossmeter/ossmeter/platform-extensions/org.ossmeter.platform.metricmanager.rascal/build.xml:368: Problem: failed to create task or type apitooling.apigeneration
Cause: The name is undefined.
Action: Check the spelling.
Action: Check that any custom tasks/types have been declared.
Action: Check that any <presetdef>/<macrodef> declarations have taken place.
------- (with "Generate p2 repository" NOT checked)

**Comment by jurgenvinju** [comment]
Hi Tiago, what is this `build.xml` file. I don't have it.

**Comment by tteixeira** [comment]
Hi Yurgen, the same here. I guess it is a file generated during the export process...

**Comment by ashimshahi** [comment]
Hi Tiago, is the eclipse PDE feature installed in your eclipse? It seems this problem happens when either the PDE feature is missing or the API tools plugin in PDE is missing from the environment.

**Comment by tteixeira** [comment]
Hi Ashim, you're right! PDE was missing from eclipse! Problem solved, thanks!
