### ISSUE TITLE
OSSMTER Platform - Uploading Odoo (formerly OpenERP). Open Source Apps To Grow Your Business

### ISSUE THREAD

**Issue by alebagnato** [ossmeter/ossmeter#26]
HI All,
I am trying to upload the GitHub project Odoo (formerly OpenERP). "Open Source Apps To Grow Your Business" on the ossmeter platform: https://github.com/odoo/odoo
but I get the following error:
"
Oh, bother...
Something has gone wrong. We're very sorry about that. The error has been logged and we'll look into as soon as possible."

Best Regards and thanks,
Alessandra

**Comment by nmatra** [comment]
I imported this project with no errors. 
![screen shot 2015-02-13 at 11 13 02](https://cloud.githubusercontent.com/assets/2675111/6186468/9ab26894-b371-11e4-9067-9b83f6fb411a.png)

**Comment by davidediruscio** [comment]
I also managed to import libreplan.

2015-02-13 12:16 GMT+01:00 nmatra notifications@github.com:

> I imported this project with no errors.
> [image: screen shot 2015-02-13 at 11 13 02]
> https://cloud.githubusercontent.com/assets/2675111/6186468/9ab26894-b371-11e4-9067-9b83f6fb411a.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ossmeter/ossmeter/issues/26#issuecomment-74239063.

## 

---

Davide Di Ruscio, PhD in Computer Science
Department of Information Engineering Computer Science and Mathematics
University of L'Aquila
Via Vetoio, Coppito I-67010 L'Aquila (Italy)
Email: davide.diruscio@univaq.it
WWW:   http://www.di.univaq.it/diruscio
Skype: davidediruscio

## Twitter: DDiRuscio

**Comment by jrwilliams** [comment]
Yep, odoo is available at https://www.ossmeter.com/projects/odoo

I'll close this issue but look into the underlying problem that is causing you to receive the error page.

**Comment by alebagnato** [comment]
many thanks!
