### ISSUE TITLE
OSSMETER Platform - uploading  LibrePlan - Open Web Planning  http://www.libreplan.com

### ISSUE THREAD

**Issue by alebagnato** [ossmeter/ossmeter#27]
Dear All,
When trying to upload on the OSSMETER Platform the following project 
LibrePlan - Open Web Planning, http://www.libreplan.com
From GitHub url https://github.com/Igalia/libreplan

I get the following error: "Oh, bother...
Something has gone wrong. We're very sorry about that. The error has been logged and we'll look into as soon as possible."

Best Regards and thanks,
Alessandra

**Comment by jrwilliams** [comment]
This imported fine for me, and is available at: https://www.ossmeter.com/projects/libreplan

I'll close this issue for now, but look into the underlying issue that's causing that error page to occur.

**Comment by alebagnato** [comment]
Thanks
