### ISSUE TITLE
WebApp: local connection to MongoDB @ Debian

### ISSUE THREAD

**Issue by tteixeira** [ossmeter/ossmeter#3]
In Debian, the localhost seems to resolve to 127.0.1.1 (http://www.debian.org/doc/manuals/debian-reference/ch05.en.html#_the_hostname_resolution). By default MongoDB is bound to 127.0.0.1, so we changed the "mongo.default.host" parameter in  conf/application.conf from localhost to 127.0.0.1.

**Comment by jrwilliams** [comment]
Each new install will need to configure their connection to Mongo as appropriate. I'll add the localhost point to a FAQ, but if you're happy, then I think we can close this issue.

**Comment by tteixeira** [comment]
Solved in v0.1.5
