### ISSUE TITLE
Java import issue

### ISSUE THREAD

**Issue by etiennebrosse** [ossmeter/ossmeter#36]
Several Java classes from org.ossmeter.platform.admin and org.ossmeter.platform.client.api import a org.restlet.data.Header class which is not part of the restlet plugin

**Comment by jrwilliams** [comment]
Fixing this currently.

**Comment by etiennebrosse** [comment]
Ok making it living ....

**Comment by jrwilliams** [comment]
Hi Etienne, Can you please pull the latest version of the dev branch and see if it fixes the issue?

**Comment by etiennebrosse** [comment]
That's perfect, as always !!!

**Comment by jrwilliams** [comment]
Grand! :)
