### ISSUE TITLE
GitHub Importer creates SVN repository clone of Git repository

### ISSUE THREAD

**Issue by jrwilliams** [ossmeter/ossmeter#37]
GitHub allows users to clone the repo using Git or SVN - as such the importer creates two VCS repositories for a project: a Git one, and an SVN one. This means that the platform will analyse _both_ repos - i.e. duplicating the work (and distorting the metrics, e.g. total LOC is doubled). 

My question is this: are there instances where the SVN repo would be different from the Git instance? If so, we might need to come up with a way to determine this. Otherwise, perhaps it would be better to simply not add the SVN repo and just use the Git one?

**Comment by davidediruscio** [comment]
An easy way for now is to consider only Git when there are both Git and SVN.

**Comment by kolovos** [comment]
As per #38 we should not be using the GitHub SVN interface
