### ISSUE TITLE
SMTP on Web App

### ISSUE THREAD

**Issue by tteixeira** [ossmeter/ossmeter#4]
SMTP seems not working when we try to request invitations. The invitation is registered in MongoDB with the corresponding "token", but it is never sent. 
We were able to create an account by reading to the "token" directly from MongoDB and using: http://127.0.0.1:9000/register?key="token"

It returns a "Forbidden" message, however you successfully created the account and are already logged in.

**Comment by jrwilliams** [comment]
This should be fixed in the latest version of the web app. It is also a good idea to use your own SMTP server rather than the one we're using during testing - I need remove those details for when we release the web app for download.

**Comment by alebagnato** [comment]
Thanks
