### ISSUE TITLE
Eclipse importer - invalid Git repo URL

### ISSUE THREAD

**Issue by jrwilliams** [ossmeter/ossmeter#43]
I've encountered a few Eclipse projects that have invalid Git URLs. I've been able to reproduce this using this code:

``` java
Mongo mongo = new Mongo();
Platform platform = new Platform(mongo);

EclipseProjectImporter im = new EclipseProjectImporter();
Project p = im.importProjectByUrl("https://projects.eclipse.org/projects/modeling.viatra", platform);

for (VcsRepository vcs : p.getVcsRepositories()) {
    System.out.println(vcs.getUrl());
}
```

Which prints:

```
http://git.eclipse.org/gitroot/viatra/org.eclipse.viatra.git
http://git.eclipse.org/gitroot/viatra/org.eclipse.viatra.modelobfuscator.git
http://git.eclipse.org/gitroot/viatra/org.eclipse.viatra.examples.git
http://git.eclipse.org/gitroot/viatra/org.eclipse.viatra2.vpm.git
```

The above URLs do not seem to work (in a web browser, or as a Git clone). Looking at https://projects.eclipse.org/projects/modeling.viatra/developer suggests the URLs should be:

```
https://git.eclipse.org/r/viatra/org.eclipse.viatra
https://git.eclipse.org/r/viatra/org.eclipse.viatra.modelobfuscator
https://git.eclipse.org/r/viatra/org.eclipse.viatra.examples
https://git.eclipse.org/r/viatra/org.eclipse.viatra2.vpm
```

I remember that a similar bug to this was fixed a while ago - perhaps we have somehow reintroduced the issue?

**Comment by jrwilliams** [comment]
Incidentally, some Git repos on Eclipse do have the same URL pattern as the invalid ones. E.g. this is valid: git://git.eclipse.org/gitroot/emf-validation/org.eclipse.emf.validation.git

I'm not familiar with the inner workings of Eclipse, but perhaps they're migrating from "/gitroot/" to "/r/" ?

**Comment by jdirocco** [comment]
Bug fixed.

**Comment by davidediruscio** [comment]
Still problems. If you import the project "epsilon" then the git url that you get is wrongly https://git.eclipse.org/r/epsilon/org.eclipse.epsilon
