### ISSUE TITLE
GitHub Importer - updating a project adds duplicate VCS repos and doesn't fully update project

### ISSUE THREAD

**Issue by jrwilliams** [ossmeter/ossmeter#46]
If a user tries to import a project that is already in the DB, the GitHub importer instead updates that project (and I assume this is the same behaviour as the importer metric providers). However, when a project is updated, its VCS repositories are duplicated. I.e. updating a project once results in two VCS repos, updating it again adds a third. 

Furthermore, updating a project also doesn't seem to fix the "user"/"repository" fields in the bug tracker (issue #7), and so we currently need to delete all GH projects and reimport them to fix this issue.

**Comment by jdirocco** [comment]
I have cleared the VCS list before update project metadata.
For issue #7 I have removed the condition to set the BTS metadata.
