### ISSUE TITLE
LibrePlan Project Monitoring  

### ISSUE THREAD

**Issue by alebagnato** [ossmeter/ossmeter#48]
Hi all,
Please find an exception I get when cliccking to my starred project LibrePlan within the two screenshots from our ossmeter.com platform.

Libreplan it is not included in my projects list since it was not me uploading it in the end but I starred it and would like to access it from my profile page.  
The other projects I listed are giving the  message "
Project Under Construction  This project is currently being analysed by OSSMETER. Please check again in a few days."

Thanking you very much in advance,
Best Regards,
alessandra
![libreplaninprofilepage](https://cloud.githubusercontent.com/assets/9965053/6412985/d0ab03b0-be8a-11e4-9527-8c341231b975.jpg)
![libreplanerror](https://cloud.githubusercontent.com/assets/9965053/6412986/d0b15bfc-be8a-11e4-9db1-5498b3f04910.jpg)

**Comment by jrwilliams** [comment]
Hi Alessandra, You were a bit unlucky there as the site was down for ~5 seconds whilst we updated it to the latest version. If you go there now it should work as expected. 
-J

**Comment by alebagnato** [comment]
Hi James,
thanks! libreplan appears without errors now, waiting to be loaded as expected
![libreplannow](https://cloud.githubusercontent.com/assets/9965053/6413628/cdc3c7e8-be91-11e4-9044-a6ba1029aeea.jpg)
