### ISSUE TITLE
Factoid descriptions need to be updated

### ISSUE THREAD

**Issue by kolovos** [ossmeter/ossmeter#72]
Proposed descriptions + comments: https://dl.dropboxusercontent.com/u/5636547/factoids-polishing.docx

**Comment by jurgenvinju** [comment]
@kolovos the WP3 metrics (in Rascal) have been updated by @basten; but we have to walk through the PHP factoids once.

**Comment by basten** [comment]
@kolovos I ran through the PHP factoids and added a clarification to one. Most of them have shared code with the Java factoids so they were already fixed by my commit e9e794b from this morning. All WP3 factoids are now updated.

**Comment by jurgenvinju** [comment]
ok thanks @basten

**Comment by jurgenvinju** [comment]
is this now closed?

**Comment by nmatra** [comment]
Yannis reported that  unit test coverage percentages are not formatted. I have not had a chance to look at this yet. But if we fix this, I think we can close this one.

**Comment by jurgenvinju** [comment]
The code for the testability factoid shows nice rounding, so I believe we are done.
