### ISSUE TITLE
Communication Channel Manager NPE during delta creation

### ISSUE THREAD

**Issue by nmatra** [ossmeter/ossmeter#80]
I get the following exception from when the communication channel manager tries to create a delta:

Project: Eclipse Modeling Project
Date: 20020905
Class: ProjectExecutor: Delta creation

``` Java
java.lang.NullPointerException at org.mapdb.BTreeMap.put(BTreeMap.java:576) at
 org.ossmeter.platform.cache.communicationchannel.CommunicationChannelDeltaCache.putDelta(CommunicationChannelDeltaCache.java:37) at 
org.ossmeter.platform.delta.communicationchannel.PlatformCommunicationChannelManager.getDelta(PlatformCommunicationChannelManager.java:101) at 
org.ossmeter.platform.delta.communicationchannel.CommunicationChannelProjectDelta.(CommunicationChannelProjectDelta.java:29) at 
org.ossmeter.platform.delta.ProjectDelta.create(ProjectDelta.java:66) at 
org.ossmeter.platform.osgi.executors.ProjectExecutor.run(ProjectExecutor.java:127) at 
org.ossmeter.platform.osgi.executors.SlaveScheduler$2.run(SlaveScheduler.java:109)
```

**Comment by yannisKork** [comment]
Trying to reproduce the problem, I importer eclipse modeling as follows:
    im.importProjectByUrl("https://projects.eclipse.org/projects/modeling", platform);

The imported project in the database is now assiciated with the following processable newsgroups:
    "newsGroupName" : "eclipse.technology.mddi",
        "newsGroupName" : "eclipse.technology.emft",
        "newsGroupName" : "eclipse.tools.uml2",
        "newsGroupName" : "eclipse.modeling",
        "newsGroupName" : "eclipse.technology.gmt.amw",
        "newsGroupName" : "eclipse.technology.gmt",
        "newsGroupName" : "eclipse.tools.emf",
        "newsGroupName" : "eclipse.modeling.gmf",

Do you know which NNTP newsgroup causes the problem? 

Thanks!

**Comment by nmatra** [comment]
No I do not.

This is what I have in the log:

```Java
INFO  [OssmeterApplication] (17:02:38): Application initialising.
INFO  [ProjectExecutor (EMF)] (17:02:39): Beginning execution.
INFO  [ProjectExecutor (EMF)] (17:02:57): Creating metric branches.
INFO  [ProjectExecutor (EMF)] (17:02:57): Created metric branches.
INFO  [ProjectExecutor (EMF)] (17:02:57): Last executed: 20021006
INFO  [ProjectExecutor (EMF)] (17:02:58): Dates: 4546
INFO  [ProjectExecutor (EMF)] (17:02:58): Date: 20021007, project: EMF
ERROR [MetricListExecutor (modeling-emf-emf, 20021007)] (17:16:03): Exception thrown during metric provider execution (threadssentiment).
java.lang.NullPointerException
        at org.ossmeter.metricprovider.trans.newsgroups.sentiment.SentimentTransMetricProvider.measure(SentimentTransMetricProvider.java:141)
        at org.ossmeter.metricprovider.trans.newsgroups.sentiment.SentimentTransMetricProvider.measure(SentimentTransMetricProvider.java:1)
        at org.ossmeter.platform.osgi.executors.MetricListExecutor.run(MetricListExecutor.java:130)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
INFO  [ProjectExecutor (EMF)] (17:16:03): Executing factoids.
WARN  [ProjectExecutor (EMF)] (17:16:05): Project in error state. Stopping execution.
INFO  [ProjectExecutor (EMF)] (17:16:05): Project execution complete. In error state: true
```

**Comment by nmatra** [comment]
No I do not. This is what I have in the log:

``` Java
INFO  [ProjectExecutor (Eclipse Modeling Project)] (17:16:35): Beginning execution.
INFO  [ProjectExecutor (Eclipse Modeling Project)] (17:16:35): Creating metric branches.
INFO  [ProjectExecutor (Eclipse Modeling Project)] (17:16:35): Created metric branches.
INFO  [ProjectExecutor (Eclipse Modeling Project)] (17:16:43): Last executed: 20020904
INFO  [ProjectExecutor (Eclipse Modeling Project)] (17:16:43): Dates: 4578
INFO  [ProjectExecutor (Eclipse Modeling Project)] (17:16:43): Date: 20020905, project: Eclipse Modeling Project
ERROR [ProjectDelta (Eclipse Modeling Project,20020905)] (17:16:43): Delta creation failed.
java.lang.NullPointerException
    at org.mapdb.BTreeMap.put(BTreeMap.java:576)
    at org.ossmeter.platform.cache.communicationchannel.CommunicationChannelDeltaCache.putDelta(CommunicationChannelDeltaCache.java:37)
    at org.ossmeter.platform.delta.communicationchannel.PlatformCommunicationChannelManager.getDelta(PlatformCommunicationChannelManager.java:101)
    at org.ossmeter.platform.delta.communicationchannel.CommunicationChannelProjectDelta.<init>(CommunicationChannelProjectDelta.java:29)
    at org.ossmeter.platform.delta.ProjectDelta.create(ProjectDelta.java:66)
    at org.ossmeter.platform.osgi.executors.ProjectExecutor.run(ProjectExecutor.java:127)
    at org.ossmeter.platform.osgi.executors.SlaveScheduler$2.run(SlaveScheduler.java:109)
ERROR [ProjectExecutor (Eclipse Modeling Project)] (17:16:43): Project delta creation failed. Aborting.
```

**Comment by yannisKork** [comment]
the problem happens because we are trying to retrieve articles from an empty newsgroup:
    newsgroup.getNewsGroupName(): eclipse.technology.mddi
    date: 20020905
    lastArticle: 0
    firstArticle: 0
    articleCount: 0
Currently, in this case the manager returns a null delta, which causes the exception above.
If I change this to return an empty delta, then we get no exception, but the platform does not know that there are no articles in this newsgroup, so it keeps asking for every day of processing and receives an empty delta as an answer.

We should think if we want to somehow notify the platform about the case of empty newsgroups. 

Please, note that this happens for one of the eight newsgroups of the project, in particular eclipse.technology.mddi.

**Comment by nmatra** [comment]
Is the newsgroup empty in general or on a particular day?

If it is empty when we import the project then I think it makes sense to return an empty delta instead of null since articles might be added in the future, and  we want to be able to monitor those.

**Comment by yannisKork** [comment]
The newsgroup is completely empty. The ids of its first and last messages are 0 and the article count on it is 0 as well. I think the best thing to do is to check for this kind of newsgroups in getfirstDate. If the newsgroup is empty then we should return today's date. Thus, the system will know that until today, there is nothing in it. it will only check for new messages in the future. If there are still no messages in subsequent tests then we should return an empty delta. If you agree, then I can do these changes.

**Comment by nmatra** [comment]
It sounds plausible. Could you please proceed with implementing and testing this? Thnx!

**Comment by yannisKork** [comment]
Fixed :)
