### ISSUE TITLE
Rascal: DateTimePrintingError for Drupal Project

### ISSUE THREAD

**Issue by nmatra** [ossmeter/ossmeter#82]
Any ideas about the following exception?

Project: Drupal
Date: 20070325
Class: MetricListExecutor: rascal.testability.java.TestCoverage

``` Java
org.rascalmpl.interpreter.control_exceptions.Throw: rascal://DateTime:555,0: DateTimePrintingError("Cannot print time with format YYYYMMdd") at 
org.rascalmpl.interpreter.control_exceptions.ControlException.reallyFillInStackTrace(ControlException.java:42) at org.rascalmpl.interpreter.control_exceptions.Throw.fillInStackTrace(Throw.java:114) at 
java.lang.Throwable.(Throwable.java:265) at java.lang.Exception.(Exception.java:66) at 
java.lang.RuntimeException.(RuntimeException.java:62) at 
org.rascalmpl.interpreter.control_exceptions.ControlException.(ControlException.java:25) at 
org.rascalmpl.interpreter.control_exceptions.Throw.(Throw.java:49) at 
org.rascalmpl.interpreter.control_exceptions.Throw.(Throw.java:69) at 
org.rascalmpl.interpreter.utils.RuntimeExceptionFactory.dateTimePrintingError(RuntimeExceptionFactory.java:262) at org.rascalmpl.library.Prelude.printDate(Prelude.java:617) at 
sun.reflect.GeneratedMethodAccessor132.invoke(Unknown Source) at 
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at 
java.lang.reflect.Method.invoke(Method.java:606) at 
org.rascalmpl.interpreter.result.JavaMethod.invoke(JavaMethod.java:233) at 
org.rascalmpl.interpreter.result.JavaMethod.call(JavaMethod.java:167) at org.rascalmpl.interpreter.result.OverloadedFunction.callWith(OverloadedFunction.java:359) at org.rascalmpl.interpreter.result.OverloadedFunction.call(OverloadedFunction.java:337) at org.rascalmpl.semantics.dynamic.Expression$CallOrTree.interpret(Expression.java:524) at org.rascalmpl.semantics.dynamic.Expression$Addition.interpret(Expression.java:134) at org.rascalmpl.semantics.dynamic.Statement$Expression.interpret(Statement.java:364) at org.rascalmpl.semantics.dynamic.Statement$Assignment.interpret(Statement.java:204) at org.rascalmpl.interpreter.result.RascalFunction.runBody(RascalFunction.java:349) at org.rascalmpl.interpreter.result.RascalFunction.call(RascalFunction.java:295) at org.rascalmpl.interpreter.result.OverloadedFunction.callWith(OverloadedFunction.java:359) at org.rascalmpl.interpreter.result.OverloadedFunction.call(OverloadedFunction.java:337) at org.rascalmpl.semantics.dynamic.Expression$CallOrTree.interpret(Expression.java:524) at org.rascalmpl.semantics.dynamic.Statement$Expression.interpret(Statement.java:364) at org.rascalmpl.semantics.dynamic.Statement$Assignment.interpret(Statement.java:204) at org.rascalmpl.interpreter.result.RascalFunction.runBody(RascalFunction.java:349) at org.rascalmpl.interpreter.result.RascalFunction.call(RascalFunction.java:268) at org.ossmeter.metricprovider.rascal.RascalMetricProvider.compute(RascalMetricProvider.java:302) at org.ossmeter.metricprovider.rascal.RascalMetricProvider.measure(RascalMetricProvider.java:206) at org.ossmeter.metricprovider.rascal.RascalMetricProvider.measure(RascalMetricProvider.java:1) at org.ossmeter.platform.osgi.executors.MetricListExecutor.run(MetricListExecutor.java:130) at 
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) at 
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) at 
java.lang.Thread.run(Thread.java:745)
```

**Comment by jurgenvinju** [comment]
yes, it most likely happens when the date provided is `0`, namely the epoch. We analyzed this two weeks ago for another bug. We should go look for collatoral damage; are other metrics also damaged due to a zero date?

**Comment by nmatra** [comment]
The same exception for Drupal on the same date for the following classes:
- MetricListExecutor: rascal.testability.java.TestOverPublicMethods
- MetricListExecutor: rascal.testability.java.NumberOfTestMethods
- MetricListExecutor: trans.rascal.OO.PHP.RR-PHP
- MetricListExecutor: trans.rascal.OO.PHP.CF-PHP
- MetricListExecutor: trans.rascal.OO.PHP.AHF-PHP
- MetricListExecutor: trans.rascal.OO.PHP.AIF-PHP
- MetricListExecutor: trans.rascal.OO.PHP.MHF-PHP
- MetricListExecutor: trans.rascal.OO.PHP.SR-PHP
- MetricListExecutor: trans.rascal.OO.PHP.PF-PHP
- MetricListExecutor: trans.rascal.OO.PHP.NOA-PHP
- MetricListExecutor: trans.rascal.OO.PHP.LCOM4-PHP
- MetricListExecutor: trans.rascal.OO.PHP.A-PHP
- MetricListExecutor: trans.rascal.OO.PHP.CBO-PHP
- MetricListExecutor: trans.rascal.OO.PHP.LCOM-PHP
- MetricListExecutor: trans.rascal.OO.PHP.NOM-PHP
- MetricListExecutor: trans.rascal.OO.PHP.MIF-PHP
- MetricListExecutor: trans.rascal.OO.PHP.NOC-PHP
- MetricListExecutor: trans.rascal.OO.PHP.TCC-PHP
- MetricListExecutor: trans.rascal.OO.PHP.LCC-PHP
- MetricListExecutor: trans.rascal.OO.PHP.Ca-PHP
- MetricListExecutor: trans.rascal.OO.java.CF-Java
- MetricListExecutor: trans.rascal.OO.java.MHF-Java
- MetricListExecutor: trans.rascal.OO.java.AHF-Java
- MetricListExecutor: trans.rascal.OO.java.AIF-Java
- MetricListExecutor: trans.rascal.PHP.StaticFieldNameResolutionHistogram
- MetricListExecutor: trans.rascal.PHP.StaticTypeNameResolutionHistogram  
- MetricListExecutor: trans.rascal.PHP.StaticMethodNameResolutionHistogram  
- MetricListExecutor: trans.rascal.activecommitters.commitsPerWeekDay  
- MetricListExecutor: trans.rascal.OO.java.LCOM-Java  
- MetricListExecutor: trans.rascal.OO.java.LCC-Java 
- MetricListExecutor: trans.rascal.OO.java.NOM-Java 
- MetricListExecutor: trans.rascal.OO.java.TCC-Java 
- MetricListExecutor: trans.rascal.OO.java.LCOM4-Java  
-  MetricListExecutor: trans.rascal.OO.java.SR-Java 
- MetricListExecutor: trans.rascal.OO.java.DIT-Java 
- MetricListExecutor: trans.rascal.OO.java.Ca-Java  
- MetricListExecutor: trans.rascal.OO.java.NOC-Java 
- MetricListExecutor: trans.rascal.OO.java.A-Java  
- MetricListExecutor: trans.rascal.OO.java.RR-Java  
- MetricListExecutor: trans.rascal.OO.java.MIF-Java 
- MetricListExecutor: trans.rascal.OO.java.NOA-Java 
- MetricListExecutor: trans.rascal.OO.java.CBO-Java

**Comment by jurgenvinju** [comment]
thoughts:
- all rascal based metrics, but not the activity metrics, just the metrics which require abstract syntax trees...
- also metrics which require a lot of memory and may trigger the GC

@ashimshahi do you have a hunch?

**Comment by nmatra** [comment]
I got the same exception for joomla-cms on 20090329.

**Comment by jurgenvinju** [comment]
Why is this blocking anything anyway? Shouldn't it just skip one day? Just trying to find out why the platform stops. The bug is hard to reproduce.

**Comment by nmatra** [comment]
The platform does not stop. But the bug is blocking the source code analysis of two projects for the industrial partners evaluation. I thought that this bug affects the validity of any subsequent measurements. If this is not the case and it only affects a single date then I will remove the blocker tag.

**Comment by jurgenvinju** [comment]
I believe it's ok indeed to remove the blocker tag; nevertheless we should fix this issue.

**Comment by ashimshahi** [comment]
@jurgenvinju I have no clue right now (it might be due to thread safety issues of SimpleDateFormat as we discussed). I have been unable to reproduce this so far but am looking for any possible cause.

**Comment by jurgenvinju** [comment]
See also #83 for a more general view on this issue.

**Comment by jurgenvinju** [comment]
I have a hunch that SimpleDateFormat is indeed the problem; we don't see the issue when we are only running the source code metrics (these are mutually exclusive and do not run in parallel), but when the platform runs with also the other metrics, such as the Nntp metrics a lot of activity with SimpleDateFormat may run in parallel with the Rascal metrics.

**Comment by jurgenvinju** [comment]
We may have fixed the bug; tell us if it happens again? This does not solve #83 which is also still lurking.

**Comment by nmatra** [comment]
This is awesome. Thanks!

**Comment by jurgenvinju** [comment]
thanks for your patience :-)
