### ISSUE TITLE
JobsWorth Project on the platform 

### ISSUE THREAD

**Issue by alebagnato** [ossmeter/ossmeter#85]
Hi all,
it would seem to exist an issue with the Jobsworth project, it appears in my profile but it is not yet considered into the analysis 
![jobworth](https://cloud.githubusercontent.com/assets/9965053/6944052/244d6b86-d892-11e4-8a5b-3005e1eccd04.jpg)
The project is on my profile ( https://ossmeter.com/projects/jobsworth)
and it would be great to compare it with LibrePlan!
Thanking you in advance
alessandra and etienne
@etiennebrosse

**Comment by nmatra** [comment]
Added.

**Comment by alebagnato** [comment]
Thanks Nikos,
Alessandra
