### ISSUE TITLE
Quality Model - Bug Metrics

### ISSUE THREAD

**Issue by alebagnato** [ossmeter/ossmeter#87]
Hi all,
I have selected in my quality model the "Bug" metrics twice (it was appearing twice in the list) as in the enclosed screenshot 
![editqm2](https://cloud.githubusercontent.com/assets/9965053/6945323/39b49d44-d899-11e4-99ba-00e2eb84472a.jpg)
I would have expected to have the same output for the two  but it would seem the two Bug metrics have different outputs. Please find enclosed the screenshot for our Drupal monitored project.
Best Regards and thanks,
alessandra
![drupal-bugs](https://cloud.githubusercontent.com/assets/9965053/6945343/5a17c6e2-d899-11e4-9acc-c5ddc2f8255a.jpg)

**Comment by davidediruscio** [comment]
May be this is due to the fact that there are some BTS and CC factoids that
have the same name ?

2015-04-01 18:04 GMT+02:00 Alessandra Bagnato notifications@github.com:

> Hi all,
> I have selected in my quality model the "Bug" metrics twice (it was
> appearing twice in the list) as in the enclosed screenshot
> [image: editqm2]
> https://cloud.githubusercontent.com/assets/9965053/6945323/39b49d44-d899-11e4-99ba-00e2eb84472a.jpg
> I would have expected to have the same output for the two but it would
> seem the two Bug metrics have different outputs. Please find enclosed the
> screenshot for our Drupal monitored project.
> Best Regards and thanks,
> alessandra
> [image: drupal-bugs]
> https://cloud.githubusercontent.com/assets/9965053/6945343/5a17c6e2-d899-11e4-9acc-c5ddc2f8255a.jpg
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ossmeter/ossmeter/issues/87.

## 

---

Davide Di Ruscio, PhD in Computer Science
Department of Information Engineering Computer Science and Mathematics
University of L'Aquila
Via Vetoio, Coppito I-67010 L'Aquila (Italy)
Email: davide.diruscio@univaq.it
WWW:   http://www.di.univaq.it/diruscio
Skype: davidediruscio

## Twitter: DDiRuscio

**Comment by alebagnato** [comment]
it can be, so where to change it?

**Comment by davidediruscio** [comment]
Hi Alessandra,

I think this cannot be changed client side.

Davide

2015-04-02 10:18 GMT+02:00 Alessandra Bagnato notifications@github.com:

> it can be, so where to change it?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ossmeter/ossmeter/issues/87#issuecomment-88820326.

## 

---

Davide Di Ruscio, PhD in Computer Science
Department of Information Engineering Computer Science and Mathematics
University of L'Aquila
Via Vetoio, Coppito I-67010 L'Aquila (Italy)
Email: davide.diruscio@univaq.it
WWW:   http://www.di.univaq.it/diruscio
Skype: davidediruscio

## Twitter: DDiRuscio

**Comment by alebagnato** [comment]
Hi Davide, thanks! ciao,alessandra
