### ISSUE TITLE
Forge importers should have common interface

### ISSUE THREAD

**Issue by jrwilliams** [ossmeter/ossmeter#9]
The forge importers should share a common interface or abstract class that defines the import methods. They do have commonly named methods (importProject, importAll, importByUrl), but we should enforce an interface.

**Comment by jdirocco** [comment]
Added a common interface in new project /platform/org.ossmeter.repository.model.importer.
Each importer implements this interface.

**Comment by jdirocco** [comment]
@jrwilliams I have changed the githubimporter's method name in order to implement IImporter interface.
If you want, I can commit this little change Change invocation in  web/org.ossmeter.platform.client.api/src/org/ossmeter/platform/client/api/ProjectImporter.java class, line 64. Let me know.
