### ISSUE TITLE
Code Understandability: Metric and Factoid results mismatch

### ISSUE THREAD

**Issue by MarcioMateus** [ossmeter/ossmeter#92]
In project IfcOpenShell the following results were obtained:
Factoid "Code Understandability" says:
![understandabilityfactoid](https://cloud.githubusercontent.com/assets/10194704/7093266/7cc23ade-dfaf-11e4-8d36-63f8e3e8b5d3.png)
Metric "Spread of files with understandability issues over the system" shows this graph:
![styleviolationgraph](https://cloud.githubusercontent.com/assets/10194704/7093283/aea0a590-dfaf-11e4-838d-e93b752c1ca5.png)

Factoid says that the situation is "getting worse in last six months" but graph shows that spread is stable.

**Comment by jurgenvinju** [comment]
Thanks for this. Do you have perhaps have a dump of the table for us to analyze? It means we may have to change a threshold or something else is going on. We need to dig in deeper!

**Comment by MarcioMateus** [comment]
We don't have any data besides the provided above. These metrics were computed in the OSSMETER platform at York.
